### ISSUE TITLE
Add unsafe escape hatches to JitFunction

### ISSUE THREAD

**Issue by timstr** [TheDan64/inkwell#389] opened 2023-01-18 04:21 UTC
Firstly, I'm loving this library and as my first introduction to working hands-on with a jit, I'm finding it delightful to use overall. Thank you so much for putting this together!

I recently tried to incorporate Inkwell's JitFunction into one of my larger projects, and the pervasive use of lifetimes gave me a lot of difficulty rewriting my many interfaces to use the lifetimes, to the point where I gave up and decided it would be easier and more efficient for me as a developer to use a small amount of unsafe code and access the raw function pointer stored inside `JitFunction`.

For more context, I am hoping to call `JitFunction` instances from multiple objects across multiple threads. The objects are created on demand by a factory of sorts, and the `JitFunction`s may be swapped out over time to perform different computations. Adding `<'ctx>` in every code location that potentially uses or stores a `JitFunction` instance is thus painful to impossible, and it is my belief that LLVM alone should be able to support this use case.

I understand that `Context`, `Module`, and `ExecutionEngine` themselves are not thread safe and I am not attempting to share them across threads. I do believe it is safe to call the jit-compiled functions from separate threads after otherwise guaranteeing that the `ExecutionEngine` stays alive and the relevant function/module is not deleted, and assuming the function implementations and invocations themselves are thread safe.

Access to the raw function pointers created by the `ExecutionEngine` would allow me to easily incorporate Inkwell into my project. I am willing to use unsafe code for this, and manually ensure that the LLVM internals stay alive long enough and are not modified concurrently. For example, in my own fork, I have added unsafe methods `as_raw` and `into_raw` to `JitFunction`:

```rust
// file src/execution_engine.rs
// [...]
pub struct JitFunction<'ctx, F> {
    _execution_engine: ExecEngineInner<'ctx>,
    inner: F,
}

impl<'ctx, F: Copy> JitFunction<'ctx, F> {
    /// Returns the raw function pointer, consuming self in the process.
    /// This function is unsafe because the function pointer may dangle
    /// if the ExecutionEngine it came from is dropped. The caller is
    /// thus responsible for ensuring the ExecutionEngine remains valid.
    pub unsafe fn into_raw(self) -> F {
        self.inner
    }

    /// Returns the raw function pointer.
    /// This function is unsafe because the function pointer may dangle
    /// if the ExecutionEngine it came from is dropped. The caller is
    /// thus responsible for ensuring the ExecutionEngine remains valid.
    pub unsafe fn as_raw(&self) -> F {
        self.inner
    }
}
```

This parallels many standard library methods such as from `Vec`, `Slice`, `Arc`, `Box`, etc, which provide unsafe access to the underlying pointers.

Thank you for your consideration, and I look forward to discussing.

**Comment by TheDan64** [comment] 2023-01-19 00:38
Hi! This seems like a dupe of #366? Also #242 for reference. 

In theory, ExecutionEngines in LLVM are thread-safe (according to the LLVM docs), however, they can take ownership of a module - and I think the module has pointers back to the parent context? So I'm not sure this it true in practice. It's been really hard to figure out a thread-safe API for EEs which is why we haven't done it yet.

**Comment by TheDan64** [comment] 2023-01-19 00:42
> I do believe it is safe to call the jit-compiled functions from separate threads after otherwise guaranteeing that the ExecutionEngine stays alive and the relevant function/module is not deleted, and assuming the function implementations and invocations themselves are thread safe.

While I'm inclined to agree, I also think this is a big assumption. It assumes that everything stays in an immutable state but in reality LLVM is just a big blob of mutable pointers and could cause a race condition if you're not careful.

Have you tried scoped threads at all? I wonder if that might work...

**Comment by TheDan64** [comment] 2023-01-19 00:43
In any case, adding raw getters is on our radar already

**Closed** 2023-01-21 05:50 UTC

**Comment by timstr** [comment] 2023-01-23 22:06
Thanks a lot @TheDan64! I'll pull in the new changes and play around. If I find time, I'll also experiment with safe and scoped uses of `JitFunction` across threads.

**Comment by timstr** [comment] 2023-02-04 23:57
@TheDan64 I want to personally thank you for your insights here. I read up on scoped lifetimes which I wasn't aware of, as well as advanced lifetimes and lifetime elision rules, and I was finally able to work with `'ctx` lifetimes throughout my code base. TL;DR, the proper use of lifetimes ultimately does suffice for my use case. Glad to have contributed though, and thanks again for this lovely project

**Comment by TheDan64** [comment] 2023-02-05 03:11
Sure thing. Thanks for the kind words :)
