### ISSUE TITLE
Segfault in test suite

### ISSUE THREAD

**Issue by hansihe** [TheDan64/inkwell#80] opened 2019-04-29 09:02 UTC
Running the test suite, always in a test after `test_attributes::test_enum_attribute_kinds`, will sometimes result in a segfault.

On my machine it happens every 20 runs or so.

I can not reproduce this when running the tests single threaded.

I can try to provide more info if this is not reproducible for anyone else.

**LLVM Version (please complete the following information):**
 - LLVM Version: 7.0
 - Inkwell Branch Used: master with llvm7.0 feature

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional Context**
```
hansihe@hansihe-XPS-13-9370:~/proj/rust/inkwell$ cargo test --features llvm7-0
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running target/debug/deps/inkwell-24beb4bfd67943ff

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/all-3b42dad18507485c

running 95 tests
test test_attributes::test_enum_attribute_kinds ... ok
error: process didn't exit successfully: `/home/hansihe/proj/rust/inkwell/target/debug/deps/all-3b42dad18507485c` (signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by TheDan64** [comment] 2019-04-29 23:37
I've been struggling to reproduce/isolate this for a long time now, so thanks for this lead!

**Comment by TheDan64** [comment] 2019-05-27 17:37
Definitely seems to be a test in the `test_attributes` file; but I haven't been able to nail a specific test down yet. GDB seems to be of little help as it appears to be a Heisenbug. I might have to disable tests one by one until the SF stops appearing

**Comment by nlewycky** [comment] 2019-07-01 04:14
I've been running `cargo test --features=llvm7-0 -- --test-threads=1` to reduce the Heisenbugginess of the tests and it seems to help for me.

**Comment by TheDan64** [comment] 2019-11-16 23:43
This may have been fixed by recent changes to how we access the global context

**Comment by TheDan64** [comment] 2019-11-22 14:24
Closing as I haven't been able to reproduce since the latest changes

**Closed by TheDan64** 2019-11-22 14:24 UTC
Labels: bug
